"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const finance_1 = require("./finance");
const sequenceUtils_1 = require("./sequenceUtils");
const stringUtils_1 = require("./stringUtils");
const userManagement_1 = require("./userManagement");
console.log("capitalize:", (0, stringUtils_1.capitalize)("typescript"));
console.log("reverseString:", (0, stringUtils_1.reverseString)("homework"));
const loanCalculator = new finance_1.Finance.LoanCalculator(250000, 12, 36);
const monthlyPayment = loanCalculator.calculateMonthlyPayment();
console.log("monthly loan payment:", monthlyPayment.toFixed(2));
const taxCalculator = new finance_1.Finance.TaxCalculator(18);
const incomeTax = taxCalculator.calculateIncomeTax(50000);
console.log("income tax:", incomeTax.toFixed(2));
const adminUser = new userManagement_1.UserManagement.Admin.AdminUser("Olena Admin", "admin@example.com", false);
console.log("admin before update:", adminUser);
adminUser.grantSuperAdmin();
console.log("admin after grant:", adminUser);
adminUser.revokeSuperAdmin();
console.log("admin after revoke:", adminUser);
console.log("fibonacci up to 50:", (0, sequenceUtils_1.generateFibonacci)(50));
console.log("prime numbers up to 50:", (0, sequenceUtils_1.generatePrimeNumbers)(50));
